# Generated by Django 5.0.4 on 2024-11-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
