# Generated by Django 5.0.4 on 2024-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_transanction_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanction',
            name='items',
            field=models.CharField(default='[]', max_length=5000),
        ),
    ]
