# Generated by Django 5.0.4 on 2024-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_transanction_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.FloatField(default=0.0),
        ),
    ]
