# Generated by Django 5.0.4 on 2024-12-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_products_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanction',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
